### ISSUE TITLE
Jinja2 view issue: 'base.html' doesn't recognize 'user' object  

### ISSUE THREAD

**Issue by samir-patnaik** [samir-patnaik/UdacityCS253#1]
Hi @onyb! Thanks for checking this out.

When the user is logged in, the view should display the username like this:

![image](https://cloud.githubusercontent.com/assets/12623042/18701623/4025f4ba-7ffb-11e6-9553-18fe6390ee33.png)
 
but it stays like this:

![image](https://cloud.githubusercontent.com/assets/12623042/18702552/d6d97d60-7fff-11e6-8300-79272e280adc.png)

 [_base.html_](https://github.com/samir-patnaik/UdacityCS253/blob/master/webapp/Problem-Statement-3/simpleblog/templates/base.html#L13):
```
<div class="login-area">
     {% if user %}
	  {{user.name}}(<a class="login-link" href="/blog/logout">logout</a>)
     {% else %}
	  <a class="login-link" href="/blog/login">login</a>
	  |
	  <a class="login-link" href="/blog/signup">signup</a>
     {% endif %}
</div>
```
The [_self.user_](https://github.com/samir-patnaik/UdacityCS253/blob/master/webapp/Problem-Statement-3/simpleblog/main.py#L83) object reads the user_id from a secure cookie:
```
def initialize(self, *a, **kw):
        webapp2.RequestHandler.initialize(self, *a, **kw)
        uid = self.read_secure_cookie('user_id')
        self.user = uid and User.by_id(int(uid))
          if self.user:
 # I wrote this test to see if the object is created correctly or not
            self.response.write('<br>motherfucker!')
            self.response.write(self.user.name) # this works!
```
This is the [ _User_ ] (https://github.com/samir-patnaik/UdacityCS253/blob/master/webapp/Problem-Statement-3/simpleblog/main.py#L233) class:
```
class User(db.Model):
    name = db.StringProperty(required = True)
    password_hash = db.StringProperty(required = True)
    email = email = db.StringProperty()

    @classmethod
    def by_id(cls, uid):
        return User.get_by_id(uid, parent = users_key())

    @classmethod
    def by_name(cls, name):
        u = User.all().filter('name =', name).get()
        return u

    @classmethod
    def register(cls, name, password, email = None):
        password_hash = make_password_hash(name, password)
        return User(parent = users_key(),
                    name = name,
                    password_hash = password_hash,
                    email = email)
    @classmethod
    def login(cls, name, password):
        u = cls.by_name(name)
        if u and validate_password_hash(name, password, u.password_hash):
            return u
```

**Comment by samir-patnaik** [comment]
_self.user_ needed to be passed into the dictionary at BlogHandler.render_str(). Issue Solved. Thanks, @onyb

**Comment by onyb** [comment]
@samir-patnaik Cheers!
